### PR TITLE
Fix error in finalize_options in Python 3

### LINKED ISSUE #44: Error in setup.py with share_dirs in adel
Reading metainfo
...version: 1.6.0
...release: 1.6
...project: alinea
...name: Alinea.Adel
...namespace: alinea
...pkg_name: alinea.adel
...package: adel
...description: ADEL
...long_description: The Adel package characterise 3D plant development for raminae crops.
...authors: Christian Fournier, Christophe Pradal
...authors_email: christophe.pradal@cirad.fr
...url: http://openalea.gforge.inria.fr
...license: Cecill-C
running develop
INSTALL LIB:  C:\Users\mlabadie\miniconda3\envs\openalea-incubator\Library\lib
Traceback (most recent call last):
  File ".\setup.py", line 26, in <module>
    setup(
  File "C:\Users\mlabadie\miniconda3\envs\openalea-incubator\lib\site-packages\setuptools\__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\mlabadie\miniconda3\envs\openalea-incubator\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\mlabadie\miniconda3\envs\openalea-incubator\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\mlabadie\miniconda3\envs\openalea-incubator\lib\distutils\dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "C:\Users\mlabadie\miniconda3\envs\openalea-incubator\lib\distutils\cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "c:\users\mlabadie\miniconda3\envs\openalea-incubator\lib\site-packages\openalea.deploy-2.1.8-py3.8.egg\openalea\deploy\command.py", line 965, in finalize_options
    for dest_dir, src_dir in d.items():

### PR DESCRIPTION
**Pull request by pradal**
I fix an error in the commands due to wrong Py2 to Py3 conversion.

This PR fix #44

### CODE REVIEW

**Comment by pradal** [comment]
@mlabadie can you test this PR, please?

**Comment by mlabadie** [comment]
@pradal I test PR installing openalea.deploy with setup.py develop on my conda environnement. It seems that HACK work. No error  message appear

**Review by pradal — COMMENTED** [review]
OK for me

**Comment by pradal** [comment]
Close issue #43 : Remove activate script on Windows.
This will be manage directly by conda packaging rather than automatically by deploy.

**Comment by mlabadie** [comment]
@pradal The problem are not resolve

> Close issue #43 : Remove activate script on Windows.
> This will be manage directly by conda packaging rather than automatically by deploy.

**Comment by mlabadie** [comment]
> Close issue #43 : Remove activate script on Windows.
> This will be manage directly by conda packaging rather than automatically by deploy.

Problem are not solve

**Comment by mlabadie** [comment]
Problem is solve thank you!!!!!!

**Pull request merged**
